export const ERROR_CODES = {
  // Authentication errors
  UNAUTHORIZED: 'UNAUTHORIZED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  INVALID_OTP: 'INVALID_OTP',
  OTP_EXPIRED: 'OTP_EXPIRED',
  RATE_LIMITED: 'RATE_LIMITED',
  INVALID_EMAIL: 'INVALID_EMAIL',

  // Authorization errors
  FORBIDDEN: 'FORBIDDEN',
  INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS',

  // Validation errors
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_INPUT: 'INVALID_INPUT',
  MISSING_REQUIRED_FIELD: 'MISSING_REQUIRED_FIELD',

  // Resource errors
  NOT_FOUND: 'NOT_FOUND',
  ALREADY_EXISTS: 'ALREADY_EXISTS',
  CONFLICT: 'CONFLICT',

  // User errors
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  EMAIL_TAKEN: 'EMAIL_TAKEN',
  USERNAME_TAKEN: 'USERNAME_TAKEN',

  // Team errors
  TEAM_NOT_FOUND: 'TEAM_NOT_FOUND',
  NOT_TEAM_MEMBER: 'NOT_TEAM_MEMBER',
  CANNOT_LEAVE_AS_OWNER: 'CANNOT_LEAVE_AS_OWNER',
  INVALID_ROLE: 'INVALID_ROLE',
  WORKSPACE_NOT_FOUND: 'WORKSPACE_NOT_FOUND',
  WORKSPACE_SLUG_TAKEN: 'WORKSPACE_SLUG_TAKEN',
  CANNOT_DELETE_PERSONAL_WORKSPACE: 'CANNOT_DELETE_PERSONAL_WORKSPACE',
  CANNOT_MODIFY_PERSONAL_WORKSPACE: 'CANNOT_MODIFY_PERSONAL_WORKSPACE',
  MUST_TRANSFER_OWNERSHIP: 'MUST_TRANSFER_OWNERSHIP',
  LAST_OWNER_PROTECTED: 'LAST_OWNER_PROTECTED',

  // Invitation errors
  INVITATION_NOT_FOUND: 'INVITATION_NOT_FOUND',
  INVITATION_EXPIRED: 'INVITATION_EXPIRED',
  INVITATION_ALREADY_ACCEPTED: 'INVITATION_ALREADY_ACCEPTED',

  // Billing errors
  SUBSCRIPTION_NOT_FOUND: 'SUBSCRIPTION_NOT_FOUND',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  PLAN_NOT_FOUND: 'PLAN_NOT_FOUND',
  SUBSCRIPTION_ALREADY_CANCELED: 'SUBSCRIPTION_ALREADY_CANCELED',
  SUBSCRIPTION_NOT_SCHEDULED_TO_CANCEL: 'SUBSCRIPTION_NOT_SCHEDULED_TO_CANCEL',
  CHECKOUT_SESSION_FAILED: 'CHECKOUT_SESSION_FAILED',
  PORTAL_SESSION_FAILED: 'PORTAL_SESSION_FAILED',
  STRIPE_CUSTOMER_NOT_FOUND: 'STRIPE_CUSTOMER_NOT_FOUND',

  // System errors
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
  DATABASE_ERROR: 'DATABASE_ERROR',
  EXTERNAL_SERVICE_ERROR: 'EXTERNAL_SERVICE_ERROR',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
